
CREATE TABLE IF NOT EXISTS similarities (
    event_id BIGINT,
    other_event_id BIGINT,
    score DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (event_id, other_event_id)
);

CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, event_id)
);