spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service

          predicates:
            - Path=/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET,POST,PUT,DELETE

server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG