spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/{application}
            - classpath:config/stats/{application}
            - classpath:config/infra/{application}
server:
  port: 0
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always