logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config.client: DEBUG
spring:
  application:
    name: stats-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    hostname: ${EUREKA_STATS_HOSTNAME:localhost}
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

