spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${REQUEST_DB_HOSTNAME:localhost}:5432/requestDb
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
server:
  port: 0
grpc:
  client:
    collector:
      address: discovery:///collector-service
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext