kafka:
  bootstrap-servers: "localhost:9092"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ANALYZER_DB_HOSTNAME:localhost}:5432/analyzerDb
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
server:
  port: 0
